//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsT1
    {
        public int ID { get; set; }
        public string NumberT1 { get; set; }
        public string NameT1 { get; set; }
        public Nullable<int> ImageT1 { get; set; }
    
        public virtual ImageT2 ImageT2 { get; set; }
    }
}
